name: CMake Test

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  cmake-test:
    runs-on: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Configure
        run: >-
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Test
        run: ctest --test-dir build --build-config Release --output-on-failure
